apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services or external users
  selector:
    app:  webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080

  #A node port exposes the service on a static port on the node IP address. 
  #NodePorts are in the 30000-32767 range by default, 
  #which means a NodePort is unlikely to match a service's intended port
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services or external users
  selector:
    app:  queue
  
  ports:
    - name: http
      port: 8161
      nodePort: 30010

  #A node port exposes the service on a static port on the node IP address. 
  #NodePorts are in the 30000-32767 range by default, 
  #which means a NodePort is unlikely to match a service's intended port
  type: NodePort





# richardchesterwood/k8s-fleetman-queue:release1